import React from 'react';

const ImageDisplay = ({ generatedImage, handleSaveImage }) => {
  if (!generatedImage) return null;

  return (
    <div className="image-result">
      <h2>Generated Image</h2>
      <div className="image-container">
        <img src={generatedImage} alt="Generated by Gemini AI" />
      </div>
      <button onClick={handleSaveImage} className="download-button">
        Download Image
      </button>
    </div>
  );
};

export default ImageDisplay;